function prim(){
    lock = document.getElementById('n1').value;
    lock = parseInt(lock);
    rec1 = lock*2
    res1 = rec1/3
    document.getElementById('b1').innerHTML = res1;
    document.getElementById('a1').innerHTML = res1;
    document.getElementById('c1').innerHTML = res1;
    rec2 = lock*4
    res2 = rec2/15
    document.getElementById('d1').innerHTML = res2;
    sum1 = lock + res1 + res1 + res1 + res2
    document.getElementById('l1').innerHTML = sum1;
    bel1 = lock*0.23
    jir1 = lock*0.06
    ugl1 = lock*0.03
    kal1 = lock*1.44
    document.getElementById('n2').innerHTML = bel1;
    document.getElementById('n3').innerHTML = jir1;
    document.getElementById('n4').innerHTML = ugl1;
    document.getElementById('n5').innerHTML = kal1;
    bel2 = res1*0.02
    jir2 = res1*0.33
    ugl2 = res1*0.04
    kal2 = res1*3.22
    document.getElementById('a2').innerHTML = bel2;
    document.getElementById('a3').innerHTML = jir2;
    document.getElementById('a4').innerHTML = ugl2;
    document.getElementById('a5').innerHTML = kal2;
    bel3 = res1*0.04
    jir3 = res1*0.01
    ugl3 = res1*0.01
    kal3 = res1*0.22
    document.getElementById('b2').innerHTML = bel3;
    document.getElementById('b3').innerHTML = jir3;
    document.getElementById('b4').innerHTML = ugl3;
    document.getElementById('b5').innerHTML = kal3;
    bel4 = res1*0.23
    jir4 = res1*0.29
    ugl4 = res1*0
    kal4 = res1*3.61
    document.getElementById('c2').innerHTML = bel4;
    document.getElementById('c3').innerHTML = jir4;
    document.getElementById('c4').innerHTML = ugl4;
    document.getElementById('c5').innerHTML = kal4;
    bel5 = res2*0
    jir5 = res2*0.86
    ugl5 = res2*0
    kal5 = res2*8.9
    document.getElementById('d2').innerHTML = bel5;
    document.getElementById('d3').innerHTML = jir5;
    document.getElementById('d4').innerHTML = ugl5;
    document.getElementById('d5').innerHTML = kal5;
    sum2 = bel1 + bel2 + bel3 + bel4 + bel5
    sum3 = jir1 + jir2 + jir3 + jir4 + jir5
    sum4 = ugl1 + ugl2 + ugl3 + ugl4 + ugl5
    sum5 = kal1 + kal2 + kal3 + kal4 + kal5
    document.getElementById('l2').innerHTML = sum2;
    document.getElementById('l3').innerHTML = sum3;
    document.getElementById('l4').innerHTML = sum4;
    document.getElementById('l5').innerHTML = sum5;
}